<?php
    /*
     * $Id$
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */

    // Page subtitle
    $lang['banner_subtitle'] =  "Area de Cuarentena";

    // Table headers
    $lang['header_spam'] =  "Sospechoso de Spam";
    $lang['header_viruses'] =  "Virus/Malware";
    $lang['header_banned_files'] =  "Archivos adjuntos Bloqueados";
    $lang['header_bad_headers'] =  "Encabezados de Mail inválidos";
    $lang['header_quarantine_contents'] =  "Contenidos en Cuarentena";

    // Text labels
    $lang['text_item'] =  "Elemento";
    $lang['text_items'] =  "Elementos";
    $lang['text_score'] =  "Puntuación";
    $lang['text_received'] =  "Recibidos";
    $lang['text_from'] =  "De";
    $lang['text_to'] =  "Para";
    $lang['text_ham'] =  "No-spam?";
    $lang['text_spam'] =  "Spam?";
    $lang['text_rescue'] =  "No-spam!";
    $lang['text_delete'] =  "Borrar";
    $lang['text_subject'] =  "Asunto";
    $lang['text_virus'] =  "Virus";
    $lang['text_file_name'] =  "Nombre del  archivo";
    $lang['text_no_subject'] =  "sin asunto";
    $lang['text_empty'] =  "Tu área de cuarentena esta vacía.";
    $lang['text_updated'] =  "Tu area de cuarentena ha sido actualizada.";
    $lang['text_of'] =  "de";
    $lang['text_spam_confirmed'] =  "%d elementos Spam sospechoso han sido confirmado";
    $lang['text_spam_rescued'] =  "%d elementos Spam han sido recuperados";
    $lang['text_spam_deleted'] =  "%d elementos Spam han sido borrados";
    $lang['text_viruses_rescued'] =  "%d elementos virus/malware han sido recuperados";
    $lang['text_viruses_deleted'] =  "%d elementos virus/malware han sido borrados";
    $lang['text_attachments_rescued'] =  "%d elementos con ficheros bloqueados han sido recuperados";
    $lang['text_attachments_deleted'] =  "%d elementos con ficheros bloqueados han sido borrados";
    $lang['text_headers_rescued'] =  "%d correos corruptos han sido recuperados";
    $lang['text_headers_deleted'] =  "%d correos corruptos han sido borrados";
    $lang['text_suspected_spam_item'] =  "Elemento de Spam sospechoso";
    $lang['text_suspected_spam_items'] =  "Elementos de Spam sospechosos";
    $lang['text_virus_item'] =  "Elemento Virus/Malware";
    $lang['text_virus_items'] =  "Elementos Virus/Malware";
    $lang['text_banned_file_item'] =  "Fichero Bloqueado";
    $lang['text_banned_file_items'] =  "Ficheros Bloqueados";
    $lang['text_bad_header_item'] =  "Elemento de Correo Corrupto";
    $lang['text_bad_header_items'] =  "Elementos de Correo Corruptos";
    $lang['text_rescue_error'] = "No se pudo recuperar el correo: ";

    // Button text
    $lang['button_confirm_spam'] =  "TODOS los elementos de esta Lista son Spam";
    $lang['button_delete_viruses'] =  " Borrar estos Virus";
    $lang['button_delete_attachments'] =  "Borrar estos Archivos";
    $lang['button_delete_headers'] =  "Borrar estos E-mails corruptos";
    $lang['button_confirm'] =  "Confirmar el estado de estos elementos";
    $lang['button_delete_all_items'] =  "Borrar TODOS los elementos en Cuarentena";

    // Link text
    $lang['link_prev'] =  "Anterior";
    $lang['link_next'] =  "Siguiente";
    $lang['link_quarantine'] =  "Volver al Menu de Cuarentena";
    $lang['link_welcome']  = "Volver a la página de Bienvenida";

?>