<?php
    /*
     * $Id$
     *
     * MAIA MAILGUARD LICENSE v.1.0
     *
     * Copyright 2004 by Robert LeBlanc <rjl@renaissoft.com>
     * All rights reserved.
     *
     * PREAMBLE
     *
     * This License is designed for users of Maia Mailguard
     * ("the Software") who wish to support the Maia Mailguard project by
     * leaving "Maia Mailguard" branding information in the HTML output
     * of the pages generated by the Software, and providing links back
     * to the Maia Mailguard home page.  Users who wish to remove this
     * branding information should contact the copyright owner to obtain
     * a Rebranding License.
     *
     * DEFINITION OF TERMS
     *
     * The "Software" refers to Maia Mailguard, including all of the
     * associated PHP, Perl, and SQL scripts, documentation files, graphic
     * icons and logo images.
     *
     * GRANT OF LICENSE
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     * 1. Redistributions of source code must retain the above copyright
     *    notice, this list of conditions and the following disclaimer.
     *
     * 2. Redistributions in binary form must reproduce the above copyright
     *    notice, this list of conditions and the following disclaimer in the
     *    documentation and/or other materials provided with the distribution.
     *
     * 3. The end-user documentation included with the redistribution, if
     *    any, must include the following acknowledgment:
     *
     *    "This product includes software developed by Robert LeBlanc
     *    <rjl@renaissoft.com>."
     *
     *    Alternately, this acknowledgment may appear in the software itself,
     *    if and wherever such third-party acknowledgments normally appear.
     *
     * 4. At least one of the following branding conventions must be used:
     *
     *    a. The Maia Mailguard logo appears in the page-top banner of
     *       all HTML output pages in an unmodified form, and links
     *       directly to the Maia Mailguard home page; or
     *
     *    b. The "Powered by Maia Mailguard" graphic appears in the HTML
     *       output of all gateway pages that lead to this software,
     *       linking directly to the Maia Mailguard home page; or
     *
     *    c. A separate Rebranding License is obtained from the copyright
     *       owner, exempting the Licensee from 4(a) and 4(b), subject to
     *       the additional conditions laid out in that license document.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
     * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
     * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
     * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
     * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
     * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
     * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
     * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
     * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     *
     */
    $lang['text_welcome_greeting'] = "Bienvenido a Maia Mailguard!";
    $lang['text_welcome_first_time'] = "Welcome to Maia Mailguard. I see this is the first time you have logged in. Please read this message completely, as it will help you understand
                                        the importantance of your participation in stopping spam.<P>
                                        First of all, to turn on spam protection quickly, just choose a level below and click on \"Change Level\".  The \"high\" level is perfectly safe, and recommended.
                                        <P>Maia Mailguard can filter your email, and can block most of the unwanted content from arriving in your inbox.  If it makes a mistake, however, not all is lost.
                                        Maia can quarantine your email away, accessable on this page, for you to \"rescue\", or \"report\" to authorities.  It also allows you to train the filter when a
                                        piece of spam gets through, by reporting it from your \"non-spam cache\" - a collection of recent emails that it considered to be good email.";
    $lang['text_welcome_intro'] = "<p>Toma medidas contra los ataques de Correo no deseado con  Maia Mailguard. Cuando un correo esta listado en el panel inferior derecho, puedes
                                    enseñar a Maia la diferencia de un correo bueno (no-spam) y un correo no deseado (spam). Por favor, tomate tu tiempo para asegurarte de que  
                                    todos los elementos (correos) están reportados correctamente; Si no tienes tiempo para hacerlo, borra todos los elementos en vez de reportarlos incorrectamente.<p>
                                    Ten presente que Maia, puede y reportara los correos confirmados como spam a otros servicios y autoridades. Al continuar con el proceso de presentación de informes, 
                                    puedes ayudar a luchar contra el spam.";
    $lang['text_welcome_current_level'] = "Nivel de protección actual:"; 
    $lang['text_welcome_custom_level'] = "**En uso Nivel Personalizado:<br>Utiliza la pantalla de configuración para administrar el nivel personalizado,<br>o si lo prefieres, selecciona un nivel predefinido arriba.";

    $lang['text_welcome_spam_blocked'] = "Elementos de SPAM bloqueados para ti.";
    $lang['text_welcome_virus_blocked'] = "Virus bloqueados para ti.";
    $lang['text_welcome_spam_blocked_system'] = "Elementos de SPAM bloqueados en todo el sistema.";
    $lang['text_welcome_virus_blocked_system'] = "Virus bloqueados en todo el sistema.";
    $lang['button_delete_all_items'] = "Borrar todos los Elementos";
    $lang['button_change_protection'] = "Cambiar nivel";

    $lang['radio_protection'] = array(  'off' => "Desactivado",
		 								'low' => "Bajo",
     									'medium' => "Medio",
										'high' => "Alto",
										'custom' => "Personalizado");

    $lang['banner_subtitle'] = "Bienvenido";

    $lang['text_cache_spam'] = "Tienes <b>%d</b> elementos en tu cache de Spam.<br>Pulsa <a href=\"%s\">AQUI</a> para reportarlo, o para recuperar un mensaje que fue erroneamente bloqueado.";
    $lang['text_cache_virus'] = "Tienes <b>%d</b> elementos en tu cache de Virus.<br>Pulsa <a href=\"%s\">AQUI</a> para borrarlo , o para recuperar un mensaje que fue erroneamente bloqueado.";
    $lang['text_cache_banned'] = "Tienes <b>%d</b> elementos en tu cache de archivos bloqueados.<br>Pulsa <a href=\"%s\">AQUI</a> para borrarlo , o para recuperar un mensaje que fue erroneamente bloqueado.";
    
    $lang['text_cache_header'] = "Tienes <b>%d</b> elementos en tu cache de Correos Corruptos.<br>Pulsa <a href=\"%s\">AQUI</a> para borrarlo , o para recuperar un mensaje que fue erroneamente bloqueado.";
    $lang['text_cache_ham'] = "Tienes <b>%d</b> elementos en tu cache de No-spam.<br>Pulsa <a href=\"%s\">AQUI</a> para ayudar a entrenar el filtro, o para reportar que es un mensaje de spam.";
    $lang['action_ham_cache']   = "Reportar/Confirmar";
    $lang['action_spam_cache']  = "Reportar/Recuperar";
    $lang['action_virus_cache'] = "Borrar/Recuperar";
    $lang['action_banned_cache'] = "Borrar/Recuperar";
    $lang['action_header_cache'] = "Borrar/Recuperar";